name: Glue Jobs CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      GLUEJOBS_PATH: src
      JUNIT_XML: junit_coverage.xml
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install test dependencies
        run: |
          python --version
          pip install -r tests/requirements-test.txt
          pip install -r src/requirements.txt

      - name: Lint CloudFormation template
        run: |
          pip install cfn-lint
          cfn-lint -c INCLUDE_CHECKS I3042 -- deploy/template.yml

      - name: Lint Python code
        run: |
          pip install flake8
          flake8 src/ --ignore F403,F405,E501

      - name: Run unit tests
        run: |
          pytest tests/ --junitxml=${{ github.workspace }}/${{ env.JUNIT_XML }}

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: ${{ github.workspace }}/${{ env.JUNIT_XML }}

#   publish:
#     needs: build-and-test
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main'
#     env:
#       GLUEJOBS_PATH: src
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Python 3.9
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.9'

#       - name: Install AWS CLI
#         run: |
#           pip install awscli

#       - name: Publish GlueJob to S3
#         env:
#           AWS_DEFAULT_REGION: us-east-1
#           BUCKET_NAME: aws-glue-artifacts-us-east-1
#         run: |
#           aws s3 cp ./src/ s3://$BUCKET_NAME/GlueJobs/ --sse AES256 --recursive --exclude "*.txt" --exclude "./tests/"
